name: Send File as Email

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Echo Email to File
      run: echo ${{ env.EMAIL }} > email.txt

    - name: Display File Contents
      run: cat email.txt

    # - name: Send Email
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     server_address: smtp.gmail.com
    #     server_port: 465
    #     username: ${{ secrets.EMAIL_USERNAME }} 
    #     password: ${{ secrets.EMAIL_PASSWORD }} 
    #     subject: "File Attachment"
    #     from: igwejude@example.com
    #     to: igwejude@example.com
    #     body: "Attached is the file you requested."
    #     attachments: |
    #       my_file.txt
