name: Update Quartz Properties

on:
  push:
    branches:
      - main  

jobs:
  update_properties:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: Dev
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Append variable to file
      run: |
        echo "${{ vars.USER_NAME }}" >> quartz.properties
        cat quartz.properties
